version: '4'
services:
  mongodb:
    image: mongo:7.0.5
    container_name: mongodb
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: my_mongo_un
      MONGO_INITDB_ROOT_PASSWORD: my_mongo_pwd
      MONGO_INITDB_DATABASE: product-service-db
    volumes:
      - ./data:/data/db
