server:
  port: 8080

spring:
  application:
    name: accounts_ms

  datasource:
    url: jdbc:h2:mem:accounts_db
    driverClassName: org.h2.Driver
    username: sa
    password: ''

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true                                        # Show SQL
    hibernate:
      ddl-auto: update
      #properties:
      #  hibernate:
      #    format_sql: true                                  # Format SQL nicely

  config:
    import: "optional:configserver:http://localhost:8071/"


# To also show bind parameter values
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG                                        # Show SQL
        orm:
          jdbc:
            bind: TRACE                                     # Show bind parameters

management:
  endpoints:
    web:
      exposure:
        include: "refresh, info"
  endpoint:
    shutdown:
      access: unrestricted
  info:
    env:
      enabled: true

#endpoints:
#  shutdown:
#    enabled: true

eureka:
  instance:
    preferIpAddress: true

  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

# To display meaning information on the eureka server
info:
  app:
    name: ACCOUNTS_MICROSERVICE
    description: Accounts Application Micro Service
    version: 1.0.0
