server:
  port: 8072

spring:
  application:
    name: api-gateway-ms

  config:
    import: "optional:configserver:http://localhost:8071/"

  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false                # to disable default routes
              lower-case-service-id: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    gateway:
      access: unrestricted

  info:
    env:
      enabled: true

eureka:
  instance:
    preferIpAddress: true

  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

# To display meaning information on the eureka server
info:
  app:
    name: API_GATEWAY_MICROSERVICE
    description: API Gateway Micro Service Instance
    version: 1.0.0

# circuit breaker configuration
resilience4j:
  circuitbreaker:
    configs:
      default:                                          # this configuration is applicable to all circuit breakers in this microservice (API Gateway)
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 2
        failureRateThreshold: 50
        waitDurationInOpenState: 10000