server:
  port: 8071

spring:
  application:
    name: config_server_ms

  profiles:
    #active: native
    active: git
  cloud:
    config:
      server:
        #native:
          #search-locations: "classpath:/config"
          #search-locations: "file:///D://workspace//Micro-Services//file-location-for-config-files"
        git:
          uri: "https://github.com/LokeshJavaTech/Micro-Services.git"
          default-label: master
          timeout: 5
          clone-on-start: true
          force-pull: true
          search-paths:
            - file-location-for-config-files

encrypt:
  key: "ENCRYPTION_AND_DECRYPTION_KEY_AND_THIS_PROPERTY_AUTOMATICALLY_ENABLES_ENCRYPT_AND_DECRYPT_ENDPOINTS"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
